### ISSUE TITLE
CSS Selector

### ISSUE THREAD

**Issue by cyouh95** [whitester/prj-rev-bwfs-dasmoto#2]
Alternatively, you could use `h2` as your CSS selector for specifying the shared properties among the 3 section headings:

```css
h2 {
  color: white;
  font-size: 32px;
}
```

https://github.com/whitester/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L12-L28
